config/routes.rb
Rails.application.routes.draw do

  root :to => 'sessions#login'
  match "signup", :to => "users#new", via: [:get,:post]
  match "login", :to => "sessions#login", via: [:get,:post]
  match "create", :to => "sessions#create", via: [:get,:post]
  match "logout", :to => "sessions#logout", via: [:get,:post]
  match "home", :to => "sessions#home", via: [:get,:post]
  match "profile", :to => "sessions#profile", via: [:get,:post]
  match "setting", :to => "sessions#setting", via: [:get,:post]

  get 'video' => 'home#index'
  resources :feedbacks

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      match 'feedbacks' => 'masters#feedback_create',via: [:post] #feedbacks.json
    end
  end

  post 'users' => 'users#create'
  get 'users' => 'users#index'

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  has_attached_file :video, #:styles => {:small => '94x58#',:medium => '188x116#',:large => '376x232#' },
    :url  => "/assets/videos/:id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/videos/:id/:style/:basename.:extension"
  validates_attachment_presence :video
  validates_attachment_size :video, :less_than => 100.megabytes
  #validates_attachment_content_type :video, :content_type => ['video/mp4', 'video/flv','video/3gp', 'video/mov','video/quicktime']
  validates_attachment :video, content_type: {content_type: ['application/x-shockwave-flash', 'application/x-shockwave-flash', 'application/flv', 'video/x-flv', 'video/mp4', 'application/x-mp4', 'application/mp4', 'video/x-mp4','video/quicktime','application/octet-stream']}
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: 'Feedback was successfully created.' }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      #params.fetch(:feedback, {})
      params.require(:feedback).permit(:feedback_text,:video)
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing Feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Feedbacks</h1>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Crew Name</th>
        <th>Passanger Name</th>
        <th>Aircraft Name</th>
        <th>Feedback Text</th>
        <th>Status</th>        
        <th>Date</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.crew_name %></td>
        <td><%= feedback.passanger_name %></td>
        <td><%= feedback.aircraft_name %></td>
        <td><%= feedback.feedback_text %></td>
        <td><%= feedback.status %></td>
        <td><%= feedback.created_at %></td>        
        <td><%= link_to 'Show Video', feedback %><%#= link_to 'Edit', edit_feedback_path(feedback) %><%#= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<br>
 <%#= video_player({:file => @feedbacks.first.video.url,  :mute => true}, {:width => 440, :height => 300}) %>
<%#= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>New Feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Showing Feedback Video</h1>
<%= video_player({:file => @feedback.video.url,  :mute => false}, {:width => 700, :height => 500}) %><br>
<%#= link_to 'Edit', edit_feedback_path(@feedback) %>
<%= link_to 'Back', feedbacks_path %>