config/routes.rb
Rails.application.routes.draw do

  root :to => 'sessions#login'
  match "signup", :to => "users#new", via: [:get,:post]
  match "login", :to => "sessions#login", via: [:get,:post]
  match "create", :to => "sessions#create", via: [:get,:post]
  match "logout", :to => "sessions#logout", via: [:get,:post]
  match "home", :to => "sessions#home", via: [:get,:post]
  match "profile", :to => "sessions#profile", via: [:get,:post]
  match "setting", :to => "sessions#setting", via: [:get,:post]

  get 'video' => 'home#index'
  resources :feedbacks

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      match 'feedbacks' => 'masters#feedback_create',via: [:post] #feedbacks.json
    end
  end

  post 'users' => 'users#create'
  get 'users' => 'users#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JetSetGo Feedback App</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'swfobject' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
<h1> </h1>
<% unless session[:user_id] %>
  <%#= link_to :Signup , :signup, class: "nav_links"%>
  <%#= link_to :Login , :login, class: "nav_links"%>	
<% else %>
  <%= link_to :Feedbacks , feedbacks_url, class: "nav_links" %> |
  <%#= link_to :Profile , :profile, class: "nav_links" %>
  <%#= link_to :Setting , :setting, class: "nav_links" %>
  <%= link_to :Users , :users, class: "nav_links" %> |
  <%= link_to :Logout , :logout, class: "nav_links" %>
<% end %>
<%= yield %>
</div>
</body>
</html>